on: 
  push:
    branches:
      - main
name: Testing Container
jobs:
  node-job:
    runs-on: ubuntu-latest
    container:
      image: node:12
    steps:
      - name: Run a command
        run: node --version
      
      
