on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - ci/*
name: environment test
jobs:
  live-job:
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY
  dev-job:
    environment: UAT
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY
